name: formatter
on: [push, pull_request]
jobs:
    black:
        name: runner / black formatter
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: psf/black@stable
              with:
                  src: "./src"
                  options: "--check --verbose"
