name: formatter
on: [push, pull_request]
jobs:
    black:
        name: runner / black formatter
        runs-on: lab:ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: "3.13"
            - uses: psf/black@stable
              with:
                  src: "./src"
                  options: "--check --verbose"
